name: LogicGates
version: '1.1.5'
main: com.piotrbednarski.logicgatesplugin.LogicGatesPlugin
api-version: '1.16'
softdepend: [ Multiverse-Core, WorldEdit, AsyncWorldEdit, FastAsyncWorldEdit ]
authors: [ Piotr Bednarski ]
description: Forget about giant Redstone logic gates. All logic gates in one block!
website: https://bednarskiwsieci.pl

commands:
  logicgates:
    description: LogicGates Plugin
    usage: /logicgates [help|menu|update|toggleinput|inspect|rotate|save|fixparticles|particles|language|author]
    aliases: [lg]
permissions:
  logicgates.place:
    description: Allows placing logic gates
    default: op
  logicgates.break:
    description: Allows breaking logic gates
    default: op
  logicgates.rotate:
    description: Allows rotating gates
    default: op
  logicgates.inspect:
    description: Allows inspecting gates
    default: op
  logicgates.admin:
    description: Admin commands
    default: op
  logicgates.give:
    description: Allows the player to receive special carpet
    default: op
  logicgates.timer:
    description: Allows changing timer cooldown
    default: op
  logicgates.toggleinput:
    description: Allows change the number of inputs
    default: op