site_name: LogicGates Docs
site_author: Piotr Bednarski
site_description: LogicGates Spigot - Plugin Documentation
site_url: https://piotrmaciejbednarski.github.io/logicgates-docs/
repo_url: https://github.com/piotrmaciejbednarski/LogicGates/
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    
plugins:
  - search
  - macros
  - mkdocs-video

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Features:
    - Logic Gates: features/gates.md
    - Redstone Mechanics: features/redstone-mechanics.md
  - Commands:
    - Basic Commands: commands/basic-commands.md
    - Permissions: commands/permissions.md
  - Tutorials:
    - First Circuit: tutorials/create-first-gate.md
    - Advanced Circuits: tutorials/advanced-circuits.md
  - Benchmark: benchmark.md
  - FAQ: faq.md