name: Gradle Publish and Release

on:
  release:
    types: [created]

jobs:
  build-publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Wymagane do utworzenia release'u
      packages: write   # Wymagane do publikacji do GitHub Packages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: "New release published to GitHub Packages"
        draft: false
        prerelease: false
        artifacts: 'build/libs/*.jar'
